version: "3.9"
services:
    db:
        image: "postgres:13.2"
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: "Your_password123"
    identityseed:
        build: 
            dockerfile: Dockerfile-Migration
            context: ./IdentityServerAspNetIdentity
        environment:
            - ConnectionStrings__DefaultConnection= Host=db;Database=Identity;Port=5432;Username=postgres;Password=Your_password123
        depends_on:
            - db